import { Category, Product } from '../types';

export const DEFAULT_PHARMACY_CATEGORIES: Category[] = [
  { id: 'cat-presc', name: 'Prescription Medicines', description: 'Hypertension, Diabetes, Cardiovascular & Specialist Rx' },
  { id: 'cat-antibiotics', name: 'Antibiotics & Anti-Infectives', description: 'Amoxicillin, Augmentin, Ciprofloxacin, Flagyl & Antimalarials' },
  { id: 'cat-otc-pain', name: 'Pain Relief & Analgesics', description: 'Paracetamol, Ibuprofen, Diclofenac, Aspirin & Antispasmodics' },
  { id: 'cat-cough-respiratory', name: 'Cough, Cold & Respiratory', description: 'Cough syrups, Lozenges, Inhalers, Allergy & Decongestants' },
  { id: 'cat-digestive', name: 'Digestive & Gastrointestinal', description: 'Antacids, Omeprazole, ORS rehydration, Laxatives & Dewormers' },
  { id: 'cat-vitamins', name: 'Vitamins & Supplements', description: 'Multivitamins, Vitamin C, Zinc, Cod Liver Oil, Calcium & Iron' },
  { id: 'cat-first-aid', name: 'First Aid & Surgical Supplies', description: 'Bandages, Gauze, Surgical spirit, Antiseptics, Gloves & Plasters' },
  { id: 'cat-skin', name: 'Dermatology & Topicals', description: 'Antifungal creams, Hydrocortisone, Calamine, Antiseptic liquid' },
  { id: 'cat-baby', name: 'Maternal & Child Health', description: 'Infant paracetamol, Gripe water, Diaper rash creams & Colic drops' },
  { id: 'cat-diagnostics', name: 'Diagnostics & Medical Devices', description: 'Glucometer test strips, BP monitors, Clinical thermometers' }
];

export const DEFAULT_PHARMACY_PRODUCTS: Product[] = [
  // 1. Antibiotics & Anti-Infectives
  {
    id: 'prod-amox-500',
    name: 'Amoxicillin 500mg Capsules (10s)',
    genericName: 'Amoxicillin Trihydrate',
    dosage: '500mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Blister Pack',
    buyingPrice: 150,
    sellingPrice: 300,
    openingStock: 100,
    currentStock: 100,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: true,
    batchNumber: 'AMX-2026-09',
    expiryDate: '2028-05-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-augmentin-625',
    name: 'Augmentin 625mg Tablets (14s)',
    genericName: 'Amoxicillin / Clavulanic Acid',
    dosage: '625mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Strip',
    buyingPrice: 850,
    sellingPrice: 1400,
    openingStock: 50,
    currentStock: 50,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'AUG-8841',
    expiryDate: '2028-03-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-azithro-500',
    name: 'Azithromycin 500mg Tablets (3s)',
    genericName: 'Azithromycin Dihydrate',
    dosage: '500mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Pack',
    buyingPrice: 220,
    sellingPrice: 450,
    openingStock: 60,
    currentStock: 60,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'AZI-4102',
    expiryDate: '2027-11-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cipro-500',
    name: 'Ciprofloxacin 500mg Tablets (10s)',
    genericName: 'Ciprofloxacin Hydrochloride',
    dosage: '500mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Blister Pack',
    buyingPrice: 180,
    sellingPrice: 350,
    openingStock: 55,
    currentStock: 55,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'CIP-9921',
    expiryDate: '2028-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-flagyl-400',
    name: 'Metronidazole (Flagyl) 400mg Tablets (20s)',
    genericName: 'Metronidazole',
    dosage: '400mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Blister Pack',
    buyingPrice: 120,
    sellingPrice: 240,
    openingStock: 80,
    currentStock: 80,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: true,
    batchNumber: 'FLG-1102',
    expiryDate: '2028-08-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-coartem-20',
    name: 'Coartem 20/120mg Malaria Tablets (24s)',
    genericName: 'Artemether / Lumefantrine',
    dosage: '20mg/120mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Box',
    buyingPrice: 420,
    sellingPrice: 700,
    openingStock: 45,
    currentStock: 45,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'COA-8821',
    expiryDate: '2028-04-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-doxy-100',
    name: 'Doxycycline 100mg Capsules (10s)',
    genericName: 'Doxycycline Hyclate',
    dosage: '100mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Blister Pack',
    buyingPrice: 130,
    sellingPrice: 260,
    openingStock: 60,
    currentStock: 60,
    stockAdded: 0,
    minStockLevel: 12,
    prescriptionRequired: true,
    batchNumber: 'DOX-3301',
    expiryDate: '2028-02-28',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-fluconazole-150',
    name: 'Fluconazole 150mg Single Dose Capsule',
    genericName: 'Fluconazole USP',
    dosage: '150mg',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-Infectives',
    unitType: 'Pack',
    buyingPrice: 90,
    sellingPrice: 200,
    openingStock: 75,
    currentStock: 75,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'FLU-7741',
    expiryDate: '2028-10-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 2. Pain Relief & Analgesics
  {
    id: 'prod-para-500',
    name: 'Paracetamol 500mg Tablets (10s)',
    genericName: 'Acetaminophen / Paracetamol',
    dosage: '500mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Blister Pack',
    buyingPrice: 20,
    sellingPrice: 50,
    openingStock: 250,
    currentStock: 250,
    stockAdded: 0,
    minStockLevel: 30,
    prescriptionRequired: false,
    batchNumber: 'PAR-1092',
    expiryDate: '2029-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-panadol-extra',
    name: 'Panadol Extra Tablets (20s)',
    genericName: 'Paracetamol + Caffeine',
    dosage: '500mg/65mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Pack',
    buyingPrice: 120,
    sellingPrice: 220,
    openingStock: 120,
    currentStock: 120,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'PAN-7734',
    expiryDate: '2028-08-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ibup-400',
    name: 'Ibuprofen 400mg Tablets (10s)',
    genericName: 'Ibuprofen',
    dosage: '400mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Blister Pack',
    buyingPrice: 40,
    sellingPrice: 100,
    openingStock: 150,
    currentStock: 150,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'IBU-5521',
    expiryDate: '2028-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-diclo-50',
    name: 'Diclofenac Sodium 50mg Tablets (10s)',
    genericName: 'Diclofenac Sodium',
    dosage: '50mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Blister Pack',
    buyingPrice: 50,
    sellingPrice: 120,
    openingStock: 100,
    currentStock: 100,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'DIC-3342',
    expiryDate: '2028-04-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aspirin-cardio',
    name: 'Cardio Aspirin 75mg Tablets (30s)',
    genericName: 'Acetylsalicylic Acid',
    dosage: '75mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Box',
    buyingPrice: 180,
    sellingPrice: 350,
    openingStock: 70,
    currentStock: 70,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'ASP-9012',
    expiryDate: '2028-11-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-buscopan-10',
    name: 'Buscopan 10mg Tablets (20s)',
    genericName: 'Hyoscine Butylbromide',
    dosage: '10mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Pack',
    buyingPrice: 260,
    sellingPrice: 460,
    openingStock: 65,
    currentStock: 65,
    stockAdded: 0,
    minStockLevel: 12,
    prescriptionRequired: false,
    batchNumber: 'BUS-4401',
    expiryDate: '2028-07-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-deep-heat',
    name: 'Deep Heat Rub Menthol Cream (35g)',
    genericName: 'Menthol + Methyl Salicylate',
    dosage: '35g tube',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Tube',
    buyingPrice: 320,
    sellingPrice: 520,
    openingStock: 50,
    currentStock: 50,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'DPH-8832',
    expiryDate: '2028-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-solpadeine',
    name: 'Solpadeine Soluble Effervescent (16s)',
    genericName: 'Paracetamol + Codeine + Caffeine',
    dosage: '500mg/8mg/30mg',
    categoryId: 'cat-otc-pain',
    categoryName: 'Pain Relief & Analgesics',
    unitType: 'Pack',
    buyingPrice: 380,
    sellingPrice: 650,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'SOL-5519',
    expiryDate: '2028-02-28',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 3. Cough, Cold & Respiratory
  {
    id: 'prod-benylin-flu',
    name: 'Benylin 4-Flu Cough Syrup (100ml)',
    genericName: 'Diphenhydramine, Paracetamol, Pseudoephedrine',
    dosage: '100ml',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Syrup (100ml)',
    buyingPrice: 380,
    sellingPrice: 580,
    openingStock: 65,
    currentStock: 65,
    stockAdded: 0,
    minStockLevel: 12,
    prescriptionRequired: false,
    batchNumber: 'BEN-9102',
    expiryDate: '2027-10-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ascoril-100',
    name: 'Ascoril Expectorant Syrup (100ml)',
    genericName: 'Bromhexine, Guaifenesin, Terbutaline',
    dosage: '100ml',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Syrup (100ml)',
    buyingPrice: 320,
    sellingPrice: 520,
    openingStock: 55,
    currentStock: 55,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'ASC-6631',
    expiryDate: '2027-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-strepsils',
    name: 'Strepsils Honey & Lemon Lozenges (16s)',
    genericName: 'Dichlorobenzyl alcohol & Amylmetacresol',
    dosage: '16 Lozenges',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Pack',
    buyingPrice: 160,
    sellingPrice: 280,
    openingStock: 90,
    currentStock: 90,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'STP-4421',
    expiryDate: '2028-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cetirizine-10',
    name: 'Cetirizine 10mg Allergy Tablets (10s)',
    genericName: 'Cetirizine Dihydrochloride',
    dosage: '10mg',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Strip',
    buyingPrice: 30,
    sellingPrice: 80,
    openingStock: 120,
    currentStock: 120,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'CET-8812',
    expiryDate: '2028-11-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-piriton-4',
    name: 'Piriton (Chlorpheniramine 4mg) Tablets (30s)',
    genericName: 'Chlorpheniramine Maleate',
    dosage: '4mg',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Strip',
    buyingPrice: 60,
    sellingPrice: 150,
    openingStock: 110,
    currentStock: 110,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'PIR-3319',
    expiryDate: '2028-05-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-otrivin-spray',
    name: 'Otrivin Adult Nasal Decongestant Spray 0.1% (10ml)',
    genericName: 'Xylometazoline Hydrochloride',
    dosage: '0.1% 10ml',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Bottle',
    buyingPrice: 480,
    sellingPrice: 720,
    openingStock: 35,
    currentStock: 35,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'OTR-9011',
    expiryDate: '2027-10-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ventolin-inhaler',
    name: 'Ventolin Evohaler Salbutamol 100mcg',
    genericName: 'Salbutamol Sulphate',
    dosage: '100mcg (200 doses)',
    categoryId: 'cat-cough-respiratory',
    categoryName: 'Cough, Cold & Respiratory',
    unitType: 'Piece',
    buyingPrice: 650,
    sellingPrice: 980,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'VEN-2201',
    expiryDate: '2028-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 4. Digestive & Gastrointestinal
  {
    id: 'prod-omeprazole-20',
    name: 'Omeprazole 20mg Capsules (14s)',
    genericName: 'Omeprazole Delayed-Release',
    dosage: '20mg',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Strip',
    buyingPrice: 120,
    sellingPrice: 250,
    openingStock: 95,
    currentStock: 95,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'OME-3301',
    expiryDate: '2028-02-28',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gaviscon-200',
    name: 'Gaviscon Double Action Liquid (200ml)',
    genericName: 'Sodium alginate, Calcium carbonate',
    dosage: '200ml',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Syrup (200ml)',
    buyingPrice: 650,
    sellingPrice: 950,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'GAV-1190',
    expiryDate: '2027-08-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ors-sachet',
    name: 'Oral Rehydration Salts (ORS) Sachet',
    genericName: 'WHO Oral Rehydration Formula',
    dosage: '20.5g powder',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Sachet',
    buyingPrice: 15,
    sellingPrice: 40,
    openingStock: 300,
    currentStock: 300,
    stockAdded: 0,
    minStockLevel: 50,
    prescriptionRequired: false,
    batchNumber: 'ORS-9932',
    expiryDate: '2029-04-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-loperamide-2',
    name: 'Loperamide (Imodium) 2mg Capsules (6s)',
    genericName: 'Loperamide Hydrochloride',
    dosage: '2mg',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Blister Pack',
    buyingPrice: 50,
    sellingPrice: 120,
    openingStock: 80,
    currentStock: 80,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'LOP-7712',
    expiryDate: '2028-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-eno-lemon',
    name: 'Eno Fruit Salt Lemon Antacid Sachet (5g)',
    genericName: 'Sodium bicarbonate + Citric acid',
    dosage: '5g sachet',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Sachet',
    buyingPrice: 30,
    sellingPrice: 60,
    openingStock: 150,
    currentStock: 150,
    stockAdded: 0,
    minStockLevel: 25,
    prescriptionRequired: false,
    batchNumber: 'ENO-4411',
    expiryDate: '2028-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-zentel-400',
    name: 'Zentel (Albendazole 400mg) Chewable (1s)',
    genericName: 'Albendazole USP',
    dosage: '400mg',
    categoryId: 'cat-digestive',
    categoryName: 'Digestive & Gastrointestinal',
    unitType: 'Pack',
    buyingPrice: 90,
    sellingPrice: 180,
    openingStock: 90,
    currentStock: 90,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'ZEN-8812',
    expiryDate: '2028-07-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 5. Vitamins & Dietary Supplements
  {
    id: 'prod-vit-c-eff',
    name: 'Vitamin C 1000mg Effervescent (20s)',
    genericName: 'Ascorbic Acid + Zinc',
    dosage: '1000mg',
    categoryId: 'cat-vitamins',
    categoryName: 'Vitamins & Supplements',
    unitType: 'Tube',
    buyingPrice: 350,
    sellingPrice: 550,
    openingStock: 70,
    currentStock: 70,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'VTC-7721',
    expiryDate: '2028-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-zinc-20',
    name: 'Zinc Sulphate 20mg Tablets (10s)',
    genericName: 'Zinc Sulphate Monohydrate',
    dosage: '20mg',
    categoryId: 'cat-vitamins',
    categoryName: 'Vitamins & Supplements',
    unitType: 'Strip',
    buyingPrice: 25,
    sellingPrice: 60,
    openingStock: 150,
    currentStock: 150,
    stockAdded: 0,
    minStockLevel: 25,
    prescriptionRequired: false,
    batchNumber: 'ZNC-5512',
    expiryDate: '2028-10-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cod-liver',
    name: 'Seven Seas Pure Cod Liver Oil (150ml)',
    genericName: 'Omega-3 + Vitamins A, D, E',
    dosage: '150ml',
    categoryId: 'cat-vitamins',
    categoryName: 'Vitamins & Supplements',
    unitType: 'Bottle',
    buyingPrice: 420,
    sellingPrice: 680,
    openingStock: 45,
    currentStock: 45,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: '7S-8832',
    expiryDate: '2027-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-neurobion-forte',
    name: 'Neurobion Forte Vitamin B Complex (30s)',
    genericName: 'Vitamins B1 + B6 + B12',
    dosage: '30 coated tablets',
    categoryId: 'cat-vitamins',
    categoryName: 'Vitamins & Supplements',
    unitType: 'Box',
    buyingPrice: 450,
    sellingPrice: 750,
    openingStock: 50,
    currentStock: 50,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'NEU-9021',
    expiryDate: '2028-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-calcium-d3',
    name: 'Calcium 500mg + Vitamin D3 Tablets (60s)',
    genericName: 'Calcium Carbonate + Cholecalciferol',
    dosage: '500mg/400IU',
    categoryId: 'cat-vitamins',
    categoryName: 'Vitamins & Supplements',
    unitType: 'Bottle',
    buyingPrice: 600,
    sellingPrice: 950,
    openingStock: 35,
    currentStock: 35,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'CAL-1192',
    expiryDate: '2028-08-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 6. First Aid & Surgical Supplies
  {
    id: 'prod-betadine-100',
    name: 'Betadine Antiseptic Solution 10% (100ml)',
    genericName: 'Povidone Iodine 10% w/v',
    dosage: '100ml',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Bottle',
    buyingPrice: 220,
    sellingPrice: 380,
    openingStock: 60,
    currentStock: 60,
    stockAdded: 0,
    minStockLevel: 12,
    prescriptionRequired: false,
    batchNumber: 'BET-4401',
    expiryDate: '2028-07-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-surgical-spirit',
    name: 'Surgical Spirit B.P. 70% (200ml)',
    genericName: 'Ethanol 70% Disinfectant',
    dosage: '200ml',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Bottle',
    buyingPrice: 90,
    sellingPrice: 180,
    openingStock: 85,
    currentStock: 85,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'SPR-2210',
    expiryDate: '2029-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-crepe-bandage',
    name: 'Crepe Bandage 7.5cm x 4.5m',
    genericName: 'Elastic Compression Bandage',
    dosage: '7.5cm',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Roll',
    buyingPrice: 60,
    sellingPrice: 130,
    openingStock: 100,
    currentStock: 100,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'CRP-1122',
    expiryDate: '2030-01-01',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sterile-gauze',
    name: 'Sterile Gauze Swabs 8-ply (5s)',
    genericName: '100% Pure Cotton Gauze',
    dosage: '10cm x 10cm',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Pack',
    buyingPrice: 40,
    sellingPrice: 90,
    openingStock: 120,
    currentStock: 120,
    stockAdded: 0,
    minStockLevel: 25,
    prescriptionRequired: false,
    batchNumber: 'GAU-3321',
    expiryDate: '2029-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cotton-wool',
    name: 'Absorbent Cotton Wool 100g',
    genericName: 'Medical Grade Cotton Wool',
    dosage: '100g',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Roll',
    buyingPrice: 80,
    sellingPrice: 160,
    openingStock: 90,
    currentStock: 90,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'COT-7741',
    expiryDate: '2030-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elastoplast',
    name: 'Elastoplast Fabric Plasters (20s)',
    genericName: 'Sterile Adhesive Wound Plaster',
    dosage: '20 strips',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Box',
    buyingPrice: 150,
    sellingPrice: 280,
    openingStock: 75,
    currentStock: 75,
    stockAdded: 0,
    minStockLevel: 15,
    prescriptionRequired: false,
    batchNumber: 'ELA-9021',
    expiryDate: '2029-03-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-latex-gloves',
    name: 'Examination Latex Gloves Powder-Free (Box of 100)',
    genericName: 'Latex Medical Gloves',
    dosage: 'Medium / 100 pcs',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Box',
    buyingPrice: 550,
    sellingPrice: 850,
    openingStock: 30,
    currentStock: 30,
    stockAdded: 0,
    minStockLevel: 5,
    prescriptionRequired: false,
    batchNumber: 'GLV-5521',
    expiryDate: '2029-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-face-masks',
    name: '3-Ply Surgical Protective Face Masks (Box of 50)',
    genericName: '3-Ply Non-Woven Surgical Mask',
    dosage: '50 masks',
    categoryId: 'cat-first-aid',
    categoryName: 'First Aid & Surgical Supplies',
    unitType: 'Box',
    buyingPrice: 250,
    sellingPrice: 450,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'MSK-7712',
    expiryDate: '2029-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 7. Diagnostics & Medical Devices
  {
    id: 'prod-thermometer',
    name: 'Digital Clinical Oral Thermometer',
    genericName: 'LCD Fast Read Clinical Thermometer',
    dosage: '1 Unit',
    categoryId: 'cat-diagnostics',
    categoryName: 'Diagnostics & Medical Devices',
    unitType: 'Piece',
    buyingPrice: 250,
    sellingPrice: 450,
    openingStock: 30,
    currentStock: 30,
    stockAdded: 0,
    minStockLevel: 5,
    prescriptionRequired: false,
    batchNumber: 'THM-5511',
    expiryDate: '2031-12-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-accu-chek',
    name: 'Accu-Chek Blood Glucose Test Strips (50s)',
    genericName: 'Blood Glucose Test Strips',
    dosage: '50 strips',
    categoryId: 'cat-diagnostics',
    categoryName: 'Diagnostics & Medical Devices',
    unitType: 'Box',
    buyingPrice: 1800,
    sellingPrice: 2600,
    openingStock: 20,
    currentStock: 20,
    stockAdded: 0,
    minStockLevel: 5,
    prescriptionRequired: false,
    batchNumber: 'ACC-8834',
    expiryDate: '2027-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-omron-bp',
    name: 'Omron Digital Upper Arm Blood Pressure Monitor',
    genericName: 'Automated Digital Sphygmomanometer',
    dosage: '1 Device with Cuff',
    categoryId: 'cat-diagnostics',
    categoryName: 'Diagnostics & Medical Devices',
    unitType: 'Piece',
    buyingPrice: 4800,
    sellingPrice: 6500,
    openingStock: 10,
    currentStock: 10,
    stockAdded: 0,
    minStockLevel: 2,
    prescriptionRequired: false,
    batchNumber: 'OMR-1092',
    expiryDate: '2032-01-01',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hcg-pregnancy',
    name: 'Rapid Response HCG Pregnancy Test Cassette',
    genericName: 'One-Step Rapid Urine HCG Test',
    dosage: '1 Test Kit',
    categoryId: 'cat-diagnostics',
    categoryName: 'Diagnostics & Medical Devices',
    unitType: 'Pack',
    buyingPrice: 50,
    sellingPrice: 150,
    openingStock: 100,
    currentStock: 100,
    stockAdded: 0,
    minStockLevel: 20,
    prescriptionRequired: false,
    batchNumber: 'HCG-4410',
    expiryDate: '2028-04-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-pulse-oximeter',
    name: 'Fingertip Pulse Oximeter Oxygen Monitor',
    genericName: 'SpO2 Pulse Oximeter Device',
    dosage: '1 Unit',
    categoryId: 'cat-diagnostics',
    categoryName: 'Diagnostics & Medical Devices',
    unitType: 'Piece',
    buyingPrice: 1100,
    sellingPrice: 1800,
    openingStock: 15,
    currentStock: 15,
    stockAdded: 0,
    minStockLevel: 3,
    prescriptionRequired: false,
    batchNumber: 'OXI-9912',
    expiryDate: '2031-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 8. Dermatology & Topicals
  {
    id: 'prod-clotrimazole',
    name: 'Clotrimazole 1% Antifungal Cream (20g)',
    genericName: 'Clotrimazole USP 1% w/w',
    dosage: '20g tube',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Tube',
    buyingPrice: 70,
    sellingPrice: 160,
    openingStock: 65,
    currentStock: 65,
    stockAdded: 0,
    minStockLevel: 12,
    prescriptionRequired: false,
    batchNumber: 'CLO-4412',
    expiryDate: '2028-05-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hydrocortisone',
    name: 'Hydrocortisone 1% Topical Cream (15g)',
    genericName: 'Hydrocortisone Acetate 1%',
    dosage: '15g tube',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Tube',
    buyingPrice: 80,
    sellingPrice: 180,
    openingStock: 50,
    currentStock: 50,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'HYD-2219',
    expiryDate: '2028-02-28',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-dettol-250',
    name: 'Dettol Antiseptic Disinfectant (250ml)',
    genericName: 'Chloroxylenol Antiseptic Liquid',
    dosage: '250ml',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Bottle',
    buyingPrice: 280,
    sellingPrice: 450,
    openingStock: 50,
    currentStock: 50,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'DET-7721',
    expiryDate: '2028-11-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-betnovate-n',
    name: 'Betnovate-N Skin Cream (15g)',
    genericName: 'Betamethasone + Neomycin',
    dosage: '15g tube',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Tube',
    buyingPrice: 220,
    sellingPrice: 390,
    openingStock: 45,
    currentStock: 45,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: true,
    batchNumber: 'BET-8819',
    expiryDate: '2028-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-calamine-lotion',
    name: 'Calamine Anti-Itch Soothing Lotion (100ml)',
    genericName: 'Calamine + Zinc Oxide',
    dosage: '100ml',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Bottle',
    buyingPrice: 140,
    sellingPrice: 260,
    openingStock: 55,
    currentStock: 55,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'CAL-3310',
    expiryDate: '2028-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-daktarin-gel',
    name: 'Daktarin Oral Gel Miconazole 2% (40g)',
    genericName: 'Miconazole 20mg/g',
    dosage: '40g tube',
    categoryId: 'cat-skin',
    categoryName: 'Dermatology & Topicals',
    unitType: 'Tube',
    buyingPrice: 420,
    sellingPrice: 680,
    openingStock: 35,
    currentStock: 35,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'DAK-9901',
    expiryDate: '2028-03-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 9. Maternal & Child Health
  {
    id: 'prod-gripe-water',
    name: 'Woodwards Gripe Water (150ml)',
    genericName: 'Dill Seed Oil, Sodium Bicarbonate',
    dosage: '150ml',
    categoryId: 'cat-baby',
    categoryName: 'Maternal & Child Health',
    unitType: 'Bottle',
    buyingPrice: 220,
    sellingPrice: 360,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: false,
    batchNumber: 'GRP-3310',
    expiryDate: '2027-10-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-calpol-100',
    name: 'Calpol Infant Suspension Paracetamol (100ml)',
    genericName: 'Paracetamol Paediatric 120mg/5ml',
    dosage: '100ml',
    categoryId: 'cat-baby',
    categoryName: 'Maternal & Child Health',
    unitType: 'Syrup (100ml)',
    buyingPrice: 340,
    sellingPrice: 520,
    openingStock: 45,
    currentStock: 45,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: false,
    batchNumber: 'CAL-9912',
    expiryDate: '2028-01-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sudocrem-60',
    name: 'Sudocrem Antiseptic Healing Diaper Cream (60g)',
    genericName: 'Zinc Oxide, Lanolin, Benzyl Benzoate',
    dosage: '60g tub',
    categoryId: 'cat-baby',
    categoryName: 'Maternal & Child Health',
    unitType: 'Tube',
    buyingPrice: 580,
    sellingPrice: 850,
    openingStock: 30,
    currentStock: 30,
    stockAdded: 0,
    minStockLevel: 6,
    prescriptionRequired: false,
    batchNumber: 'SUD-4412',
    expiryDate: '2028-08-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-infacol-drops',
    name: 'Infacol Infant Colic Relief Drops (50ml)',
    genericName: 'Simeticone 40mg/ml',
    dosage: '50ml bottle with dropper',
    categoryId: 'cat-baby',
    categoryName: 'Maternal & Child Health',
    unitType: 'Bottle',
    buyingPrice: 480,
    sellingPrice: 750,
    openingStock: 25,
    currentStock: 25,
    stockAdded: 0,
    minStockLevel: 5,
    prescriptionRequired: false,
    batchNumber: 'INF-1102',
    expiryDate: '2028-03-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 10. Prescription Medicines (Chronic & Specialty)
  {
    id: 'prod-amlodipine-5',
    name: 'Amlodipine 5mg Blood Pressure Tablets (30s)',
    genericName: 'Amlodipine Besylate',
    dosage: '5mg',
    categoryId: 'cat-presc',
    categoryName: 'Prescription Medicines',
    unitType: 'Box',
    buyingPrice: 180,
    sellingPrice: 380,
    openingStock: 55,
    currentStock: 55,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'AML-4419',
    expiryDate: '2028-04-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-metformin-500',
    name: 'Metformin 500mg Diabetes Tablets (100s)',
    genericName: 'Metformin Hydrochloride',
    dosage: '500mg',
    categoryId: 'cat-presc',
    categoryName: 'Prescription Medicines',
    unitType: 'Box',
    buyingPrice: 350,
    sellingPrice: 650,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'MET-8821',
    expiryDate: '2028-07-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-losartan-50',
    name: 'Losartan Potassium 50mg Tablets (30s)',
    genericName: 'Losartan Potassium',
    dosage: '50mg',
    categoryId: 'cat-presc',
    categoryName: 'Prescription Medicines',
    unitType: 'Box',
    buyingPrice: 280,
    sellingPrice: 520,
    openingStock: 45,
    currentStock: 45,
    stockAdded: 0,
    minStockLevel: 10,
    prescriptionRequired: true,
    batchNumber: 'LOS-5510',
    expiryDate: '2028-09-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-atorvastatin-20',
    name: 'Atorvastatin 20mg Cholesterol Tablets (30s)',
    genericName: 'Atorvastatin Calcium',
    dosage: '20mg',
    categoryId: 'cat-presc',
    categoryName: 'Prescription Medicines',
    unitType: 'Box',
    buyingPrice: 350,
    sellingPrice: 680,
    openingStock: 40,
    currentStock: 40,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: true,
    batchNumber: 'ATO-7731',
    expiryDate: '2028-06-30',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-glibenclamide-5',
    name: 'Glibenclamide 5mg Diabetes Tablets (100s)',
    genericName: 'Glibenclamide',
    dosage: '5mg',
    categoryId: 'cat-presc',
    categoryName: 'Prescription Medicines',
    unitType: 'Box',
    buyingPrice: 220,
    sellingPrice: 450,
    openingStock: 35,
    currentStock: 35,
    stockAdded: 0,
    minStockLevel: 8,
    prescriptionRequired: true,
    batchNumber: 'GLI-3302',
    expiryDate: '2028-03-31',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
